export const BRANCHES = [
  "Robinson Sukhumvit",
  "Max Valu Srinakarin",
  "Imperial Samrong",
  "Mahboonkrong",
  "Seacon Bangkae",
  "Central Chonburi",
  "Pata Pinklao",
  "Seacon Square 1",
  "Phaholyothin Place",
  "Future Park Rangsit",
  "Chiangmai Night Bazaar",
  "Center One",
  "Major Cineplex Pinklao",
  "Ploenchit Center",
  "SCB Park",
  "Phuket",
  "Sathon Nakorn",
  "Bumrungrad",
  "Passione Shopping Destination Rayong",
  "Patong Beach, Phuket",
  "Central Rama 3",
  "Major Cineplex Sukhumvit 61",
  "Zeer Rangsit",
  "Ratchadamnoen",
  "Bangchak Bangna Km.6.5",
  "Central Ladprao",
  "Major Cineplex Ratchayothin",
  "Pacific Park Sriracha",
  "Tesco Srinakarin",
  "IT Mall Fortune Town",
  "PTT Motorway Outbound",
  "Lee Gardens Plaza Hadyai",
  "Tesco Rama 4",
  "Tesco Changwattana",
  "Tesco Sukhumvit 50",
  "Tesco Laksi",
  "PTT Motorway Inbound",
  "The Mall Korat",
  "Bangchak Rama 4",
  "Chaweng Beach, Koh Samui",
  "Fairy Plaza Khonkaen",
  "Mini Siam",
  "Tesco Rama 3",
  "Tesco Prachachuen",
  "PTT Ayudhaya",
  "Lamai Beach , Koh Samui",
  "Tesco Phuket",
  "Tesco Bangkapi",
  "Big C Tiwanon",
  "Krabi",
  "Siam Paragon 1",
  "Esplanade Ratchada",
  "The Avenue Pattaya",
  "The Avenue Ratchayothin",
  "Twilight Of Bangla, Phuket",
  "Paseo Ladkrabang",
  "Chaweng Garden, Koh Samui",
  "Tesco Town in Town",
  "Yes Bangphli",
  "Max Valu Laksi",
  "Max Valu Nawamin",
  "M Park Rangsit Klong 3",
  "Nawamin City Avenue",
  "Big C Extra Sukhaphiban 5",
  "Jungceylon 1, Patong Phuket",
  "Khaolak Plaza, Pang-Nga",
  "Central Pinklao",
  "Big C Extra Lumlukka Klong 4",
  "Esplanade Rattanathibeth",
  "UD Town, Udorn Thani",
  "Central Khonkaen",
  "Imm Thapae Chiangmai",
  "Pattaya Klang",
  "Kanchanapisek - Kallapapruek",
  "Rajchapruek Rattanathibeth",
  "The Circle Rajchapruek",
  "Tesco Choengtalay Phuket",
  "Central Festival Pattaya 1",
  "Supreme Samsen",
  "Central Festival Phuket",
  "The Market Village Kaoyai",
  "Amorini, Siam Park",
  "Meechok Chiangmai",
  "PTT Rama 2 Km.35",
  "Platinum Novotel",
  "Central Chiangrai",
  "The Nine Rama 9",
  "Sadao Dannok",
  "Kaosan Road 2",
  "Nakornchaisri, Nakornpathom",
  "M Park Rama 2",
  "Central Phitsanulok",
  "Central Rama 9",
  "Shibuya Pratunam",
  "Porto Chino",
  "Ladprao 116",
  "Central Udornthani",
  "IBiz Nakornsrithammarat",
  "Mega Bangna 1",
  "The Coast Bangna",
  "Mega Wangburapa",
  "Diana Hadyai",
  "Kanjanapisek Bangyai",
  "Star Avenue Chiangmai",
  "Phaholyothin Wangnoi Ayudhaya",
  "Grand Five Nana",
  "Huahin Market Village",
  "Central Lampang",
  "Ubon Square",
  "Chic Republic Ratchapruek",
  "Paseo Sukhapiban 3",
  "Central Ubonrajthani",
  "Phaholyothin Rangsit",
  "Victoria Garden - Petchkasem 69",
  "BB Bangyai Market",
  "M-Park Kanchanaburi",
  "PTT Bangpoon OB (Expert)",
  "Rajburi Petchkaseam",
  "Star Mahidol Chiangmai",
  "Central Haadyai",
  "VC Pattaya",
  "PTT Nakhonsawan",
  "PTT 345 Outbound",
  "Hangdong Chiangmai",
  "Glas Haus Ratchada 17",
  "M-Park Nakhonsawan",
  "Suandok Hospital",
  "Tesco Bangyai",
  "Nichada",
  "PTT 345 Inbound",
  "Bangchak Nakornpratom Inbound",
  "Robinson Samutprakarn",
  "Metro West Town",
  "Kad Farang",
  "Bangchak Cha Am",
  "PTT Wangnoi Ayudhaya Inbound",
  "Paseo Park",
  "Tesco Hatyai",
  "Tesco Ramindra (DT)",
  "PTT Suphanburi",
  "Suanlum Night Bazaar Ratchada",
  "EmQuartier",
  "Market Village SVB",
  "Tulip Square",
  "PTT Thungsong",
  "Wufoo Khonkaen",
  "Pattaya Post Office",
  "Union Mall",
  "Bangchak Banpho 1 Outbound",
  "Bangchak Rayong",
  "PTT Wangmanao",
  "Serm Thai Complex Mahasarakam",
  "Klang Rayong",
  "Big C Bangphli",
  "Buriram's Castle",
  "Big C Lopburi",
  "PTT Nakornchaisri",
  "Bukis Phuket",
  "Bangchak Pakchong",
  "The Mall Korat 2",
  "Big C Suksawas",
  "AC Market Saimai",
  "Nimmanhaemin Road, Chiangmai",
  "The Bay",
  "Central Marina Pattaya",
  "1st Avenue - Zhlian",
  "Bangchak Bangna-Trad Km.17",
  "Krabi Beachfront",
  "Robinson Srisaman",
  "Show DC Rama 9",
  "Robinson Petchburi",
  "Harbor Mall Laemchabang",
  "Pattaya Soi Buakao",
  "Bangsaen",
  "Century Onnuch",
  "Bangchak Cholburi Bypass",
  "Bangchak Srinakarin",
  "Porto Go BangPa-in",
  "Phi Phi Island",
  "Big C Nakornpathom",
  "Tukkom Pattaya",
  "Ibis Kaosan",
  "Tesco Chantaburi",
  "Palladium",
  "Market Place Dusit",
  "Shell Ramindra",
  "Whizdom 101",
  "Bangchak Wangmanao",
  "Silom 64",
  "ACTIVE PARK, MUANGTHONG THANI",
  "The Mall Thaphra",
  "Market Place Pracha Uthit",
  "Market Place Krungthepkreeta",
  "THONBURI MARKET PLACE (DRIVE-THRU)",
  "PT BOROM SALAYA (DRIVE-THRU)",
  "MAHIDOL SALAYA (DRIVE-THRU)",
  "Bangchak Saraburi in town",
  "Suvarnabhumi Inter Airside (D)",
  "Suvarnabhumi Inter Airside (F)",
  "SVB Airport Inter Landside",
  "LIDO PATTAYA",
  "The Mall Bangkapi",
  "Walking Street Pattaya",
  "The Mall Bangkae",
  "Suvarnabhumi Inter Airside (SAT-1)",
  "SVB Domestic Airside",
  "PTT BOROMRATCHONNANEE (DRIVE-THRU)",
  "LIAB KLONG SONG",
  "Big C Rajdamri",
  "Jungceylon 2 (Sai 3), Patong Phuket",
  "Rama 2 Nakornthon",
  "Holiday Inn Express",
  "Mega Bangna -IKEA",
  "S-Park Klong Luang",
  "Phuket Inter Airside",
  "Central Bangrak",
  "Chiangmai Airport",
  "Donmueang Inter Airside",
  "Donmueang Inter Landside",
  "BB Building Asoke",
  "Bangrak Beach, Koh Samui",
  "Again Pattaya",
  "Fisherman Village, Koh Samui",
  "Tops Kamala Phuket",
  "RAMA 3",
  "Jomtien Beach Pattaya",
  "Suwinthawong",
  "Paragon Cineplex (5th Fl.)",
  "Major Rangsit",
  "Bangchak Sukhaphiban 3",
  "Sukhumvit 11",
  "Rawai Beach Phuket",
  "PTT Kasetnawamin",
  "Suvarnabhumi Inter Airside (B)",
  "Bukis Point Pattaya",
  "Haad Rin, Koh Pha-Ngan",
  "Phuket Domestic Airside",
  "Donmueng Domestic Airside (P3)",
  "Tops Khao Phra Tamnak Pattaya",
  "Long Beach Wong Amat Pattaya",
  "PTT Vibhavadi Rangsit Rab 1",
  "La Flora, Patong Phuket",
  "Kaosan Road 1",
  "Tesco Amata Nakorn",
  "Donmueng Domestic Airside"
];
