services:
  app:
    container_name: trainingsurvey-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - TZ=Asia/Bangkok
